### ISSUE TITLE
corrupted islands constantly

### ISSUE THREAD

**Issue by Aarpn** [BG-Software-LLC/WildInspect#14]
### Minecraft's Version

1.8.8

### Plugin's Version

dev version b306 (note ive never had an issue like this with the latest stable version)

### Describe the bug

Sometimes when I restart my server and load it back up, all islands are done/corrupted and all placeholders and stuff delete, I know its superiorskyblock as the issue as if I delete the database, it all goes back to how it should be

### To Reproduce

idk tbh, its random

### Additional Information

19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Enabling the module bank...
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Finished enabling the module bank (Took 7ms)
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Enabling the module missions...
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission woodcutter
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission cobble-miner
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission birthday
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission first-island
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission first-invite
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission mobs-killer
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission enchanter
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission add-member
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission 10k-worth
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Registered mission dragon-killer
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Finished enabling the module missions (Took 67ms)
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Enabling the module generators...
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Finished enabling the module generators (Took 4ms)
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Enabling the module upgrades...
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Finished enabling the module upgrades (Took 14ms)
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Loading messages started...
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2]  - Found 676 messages in the language files.
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Loading messages done (Took 101ms)
19.09 00:35:00 [Server] INFO [SuperiorSkyblock2] Successfully loaded schematic s3.schematic (SuperiorSkyblock)
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Successfully loaded schematic sb2.schematic (SuperiorSkyblock)
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Successfully loaded schematic s1.schematic (SuperiorSkyblock)
19.09 00:35:01 [Server] WARN com.bgsoftware.superiorskyblock.utils.exceptions.HandlerLoadException: java.lang.NullPointerException
19.09 00:35:01 [Server] WARN at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.handleExceptions(MenusProvider_Default.java:545)
19.09 00:35:01 [Server] WARN at com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.initializeMenus(MenusProvider_Default.java:77)
19.09 00:35:01 [Server] WARN at com.bgsoftware.superiorskyblock.menu.MenusHandler.loadData(MenusHandler.java:27)
19.09 00:35:01 [Server] WARN at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:481)
19.09 00:35:01 [Server] WARN at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:240)
19.09 00:35:01 [Multicraft] Skipped 21 lines due to rate limit (30/s)
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Finished players!
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Starting to load islands...
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Finished islands!
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Starting to load grid...
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Finished grid!
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Starting to load bank transactions...
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Finished bank transactions!
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Starting to load stacked blocks...
19.09 00:35:01 [Server] INFO [SuperiorSkyblock2] Finished stacked blocks!

**Comment by Aarpn** [comment]
wrong place
