### ISSUE TITLE
Update to CoreProtect 22.0

### ISSUE THREAD

**Issue by B1RDOW** [BG-Software-LLC/WildInspect#27]
### Minecraft's Version

Paper 1.20.1

### Plugin's Version

Lasted dev build #2

### Describe the bug

There is no block data on container transactions because in the new Coreprotect ChestTransactionLookup.class performLookup is List<String> instead of String[]

### To Reproduce

Install CoreProtect 22.0 and check container transactions

### Additional Information

![Screenshot_407](https://github.com/BG-Software-LLC/WildInspect/assets/61405779/4acc6f66-013a-4e54-8c6a-ab4ec34bf395)

**Comment by B1RDOW** [comment]
![Screenshot_408](https://github.com/BG-Software-LLC/WildInspect/assets/61405779/994f1456-2caa-474c-97c1-4ee51a5f1a4e)
![Screenshot_409](https://github.com/BG-Software-LLC/WildInspect/assets/61405779/849c79ac-8d95-4684-a54e-ee98505481f7)

**Comment by OmerBenGera** [comment]
I suspect you have hideOps enabled, as it works fine for me.

**Comment by gre3x** [comment]
My server also has this issue and we have disabled hideOps. When clicking on a chest, I get this error in console:
```11.11 12:45:33 [Server] [WARN] org.apache.commons.lang.UnhandledException: Plugin WildInspect v2.4.1.2 generated an exception while executing task 2389646
11.11 12:45:33 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
11.11 12:45:33 [Server] [INFO] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11.11 12:45:33 [Server] [INFO] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11.11 12:45:33 [Server] [INFO] at java.lang.Thread.run(Thread.java:748)
11.11 12:45:33 [Server] [INFO] Caused by: java.lang.NoSuchMethodError: net.coreprotect.database.Lookup.chestTransactions(Ljava/lang/String;Ljava/sql/Statement;Lorg/bukkit/Location;Lorg/bukkit/command/CommandSender;IIZ)Ljava/lang/String;
11.11 12:45:33 [Server] [INFO] at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performChestLookup(CoreProtectHook.java:54)
11.11 12:45:33 [Server] [INFO] at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:175)
11.11 12:45:33 [Server] [INFO] at com.bgsoftware.wildinspect.coreprotect.CoreProtect.performDatabaseLookup(CoreProtect.java:92)
11.11 12:45:33 [Server] [INFO] at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:76)
11.11 12:45:33 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:60)
11.11 12:45:33 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
11.11 12:45:33 [Server] [INFO] ... 3 more```

**Comment by Redwolf223** [comment]
Same problem for me

**Comment by OmerBenGera** [comment]
You are both using a really old version of CoreProtect, that's why it happens.
Open a new issue regarding this, as this is not related to the original issue reported here.

@B1RDOW Any news regarding this?
