### ISSUE TITLE
doesn't work with container blocks.

### ISSUE THREAD

**Issue by Dot0420** [BG-Software-LLC/WildInspect#30]
### Minecraft's Version

Paper 1.20.1 

### Plugin's Version

WildInspect-2024.1-b8
CoreProtect-22.2

### Describe the bug

For example, if you left-click on a chest, it works, but if you right-click, it doesn't work.

### To Reproduce

Insert and remove items from container blocks and right-click

### Additional Information

`[16:03:35 WARN]: [WildInspect] Plugin WildInspect v2024.1 generated an exception while executing task 12922
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
        at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performChestLookup(CoreProtectHook.java:52) ~[WildInspect-2024.1.jar:?]
        at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:175) ~[WildInspect-2024.1.jar:?]
        at com.bgsoftware.wildinspect.coreprotect.CoreProtect.performDatabaseLookup(CoreProtect.java:92) ~[WildInspect-2024.1.jar:?]
        at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:76) ~[WildInspect-2024.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[plazma-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Dot0420** [comment]
solved, thank you!
