### ISSUE TITLE
Folia Error (Integrations with Lands)

### ISSUE THREAD

**Issue by YusakiDev** [BG-Software-LLC/WildInspect#31]
### Minecraft's Version

This server is running Folia version git-Folia-"25ee657" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25ee657)

### Plugin's Version

WildInspect-2024.2-b12

### Describe the bug

[00:22:43 ERROR]: Could not pass event PlayerInteractEvent to WildInspect v2024.2-b12
java.lang.NoClassDefFoundError: me/angeschossen/lands/api/role/enums/RoleSetting
        at com.bgsoftware.wildinspect.hooks.ClaimsProvider_Lands.hasRegionAccess(ClaimsProvider_Lands.java:34) ~[WildInspect-2024.2-b12.jar:?]
        at com.bgsoftware.wildinspect.handlers.HooksHandler.getRegionAt(HooksHandler.java:35) ~[WildInspect-2024.2-b12.jar:?]
        at com.bgsoftware.wildinspect.coreprotect.CoreProtect.performLookup(CoreProtect.java:39) ~[WildInspect-2024.2-b12.jar:?]
        at com.bgsoftware.wildinspect.listeners.BlockListener.onBlockClick(BlockListener.java:33) ~[WildInspect-2024.2-b12.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1197.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"25ee657"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1895) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1646) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.angeschossen.lands.api.role.enums.RoleSetting
        ... 26 more

### To Reproduce

use wildinspect in your land

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by YusakiDev** [comment]
This seems to be fixed
